# Generated by Django 4.0.1 on 2022-01-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_time',
            new_name='updated_at',
        ),
    ]
